use customer_shopping_db;

-- Customer Shopping Behavior Analysis — SQL Business Questions

-- Q1. How many total customers are in the dataset, and what is the total revenue?
SELECT COUNT(*) AS total_customers, ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer;

-- Q2. What is the average purchase amount and average review rating overall?
SELECT ROUND(AVG(purchase_amount), 2) AS avg_purchase, ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer;

-- Q3. How many customers used a discount on their purchase?
SELECT COUNT(*) AS discount_customers
FROM customer
WHERE discount_applied = 'Yes';

-- Q4. What is the total revenue generated by each product category?
SELECT category, ROUND(SUM(purchase_amount), 2) AS category_revenue
FROM customer
GROUP BY category
ORDER BY category_revenue DESC;

-- Q5. How do male and female customers compare in spend and rating?
SELECT gender,
       COUNT(*) AS num_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY gender;

-- Q6. What are the top 5 most frequently purchased items?
SELECT item_purchased, COUNT(*) AS times_purchased
FROM customer
GROUP BY item_purchased
ORDER BY times_purchased DESC
LIMIT 5;

-- Q7. Which shipping type is used most often, and what's the average spend for each?
SELECT shipping_type,
       COUNT(*) AS times_used,
       ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY shipping_type
ORDER BY times_used DESC;

-- Q8. Which payment methods have an average spend above $50?
SELECT payment_method, ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY payment_method
HAVING AVG(purchase_amount) > 50;

-- Q9. Which customers spent above the overall average despite using a discount?
SELECT customer_id, purchase_amount
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
AND discount_applied = 'Yes';

-- Q10. Segment customers into New, Returning, and Loyal based on purchase history.
SELECT
    CASE
        WHEN previous_purchases <= 5 THEN 'New'
        WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS num_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY customer_segment;
